<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TransacaoFinanceira.Domain\TransacaoFinanceira.Domain.csproj" />
  </ItemGroup>
</Project>
